<?php

return [
    'php' => [
        ['adminPostsActionsPage (\s|"|\')', 'adminPostsActionsPage ', 'adminPostsActions', '2.24', 'https://open-time.net/post/2022/11/17/Adapter-son-code-pour-la-224-n-28'],
        ['adminCommentsActionsPage(\s|"|\')', 'adminCommentsActionsPage', 'adminCommentsActions', '2.24', 'https://open-time.net/post/2022/11/17/Adapter-son-code-pour-la-224-n-28'],
        ['adminPagesActionsPage(\s|"|\')', 'adminPagesActionsPage', 'adminPagesActions', '2.24', 'https://open-time.net/post/2022/11/17/Adapter-son-code-pour-la-224-n-28'],

        ['coreBeforeLoadingNsFiles(\s|"|\')', 'coreBeforeLoadingNsFiles', 'coreBeforeLoadingNsFilesV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['coreCommentSearch(\s|"|\')', 'coreCommentSearch', 'coreCommentSearchV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['corePostSearch(\s|"|\')', 'corePostSearch', 'corePostSearchV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],

        ['publicAfterContentFilter(\s|"|\')', 'publicAfterContentFilter', 'publicAfterContentFilterV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['publicAfterDocument(\s|"|\')', 'publicAfterDocument', 'apublicAfterDocumentV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['publicBeforeContentFilter(\s|"|\')', 'publicBeforeContentFilter', 'publicBeforeContentFilterV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['publicBeforeDocument(\s|"|\')', 'publicBeforeDocument', 'apublicBeforeDocumentV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['publicBeforeReceiveTrackback(\s|"|\')', 'publicBeforeReceiveTrackback', 'publicBeforeReceiveTrackbackV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['publicContentFilter(\s|"|\')', 'publicContentFilter', 'publicContentFilterV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['publicPrepend(\s|"|\')', 'publicPrepend', 'publicPrependV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['templateAfterBlock(\s|"|\')', 'templateAfterBlock', 'templateAfterBlockV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['templateAfterValue(\s|"|\')', 'templateAfterValue', 'templateAfterValueV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['templateBeforeBlock(\s|"|\')', 'templateBeforeBlock', 'templateBeforeBlockV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['templateBeforeValue(\s|"|\')', 'templateBeforeValue', 'templateBeforeValueV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['templateInsideBlock(\s|"|\')', 'templateInsideBlock', 'templateInsideBlockV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['tplAfterData(\s|"|\')', 'tplAfterData', 'tplAfterDataV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['tplBeforeData(\s|"|\')', 'tplBeforeData', 'tplBeforeDataV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],

        ['adminBlogFilter(\s|"|\')', 'adminBlogFilter', 'adminBlogFilterV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminBlogListHeader(\s|"|\')', 'adminBlogListHeader', 'adminBlogListHeaderV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminBlogListValue(\s|"|\')', 'adminBlogListValue', 'adminBlogListValueV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminBlogPreferencesForm(\s|"|\')', 'adminBlogPreferencesForm', 'adminBlogPreferencesFormV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminBlogsActionsPage(\s|"|\')', 'adminBlogsActionsPage', 'adminBlogsActionsPageV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminColumnsLists(\s|"|\')', 'adminColumnsLists', 'adminColumnsListsV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminCommentFilter(\s|"|\')', 'adminCommentFilter', 'adminCommentFilterV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminCommentListHeader(\s|"|\')', 'adminCommentListHeader', 'adminCommentListHeaderV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminCommentListValue(\s|"|\')', 'adminCommentListValue', 'adminCommentListValueV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminCommentsActions(\s|"|\')', 'adminCommentsActions', 'adminCommentsActionsV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminCommentsActionsPage(\s|"|\')', 'adminCommentsActionsPage', 'adminCommentsActionsPageV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminCommentsSpamForm(\s|"|\')', 'adminCommentsSpamForm', 'adminCommentsSpamFormV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminCurrentThemeDetails(\s|"|\')', 'adminCurrentThemeDetails', 'adminCurrentThemeDetailsV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminDashboardContents(\s|"|\')', 'adminDashboardContents', 'adminDashboardContentsV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminDashboardFavorites(\s|"|\')', 'adminDashboardFavorites', 'adminDashboardFavoritesV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminDashboardFavs(\s|"|\')', 'adminDashboardFavs', 'adminDashboardFavsV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminDashboardFavsIcon(\s|"|\')', 'adminDashboardFavsIcon', 'adminDashboardFavsIconV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminDashboardItems(\s|"|\')', 'adminDashboardItems', 'adminDashboardItemsV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminDashboardOptionsForm(\s|"|\')', 'adminDashboardOptionsForm', 'adminDashboardOptionsFormV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminFiltersLists(\s|"|\')', 'adminFiltersLists', 'adminFiltersListssV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminMediaFilter(\s|"|\')', 'adminMediaFilter', 'adminMediaFilterV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminPageFooter(\s|"|\')', 'adminPageFooter', 'adminPageFooterV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminPagesActionsPage(\s|"|\')', 'adminPagesActionsPage', 'adminPagesActionsPageV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminPagesListHeader(\s|"|\')', 'adminPagesListHeader', 'adminPagesListHeaderV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminPagesListValue(\s|"|\')', 'adminPagesListValue', 'adminPagesListValueV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminPostFilter(\s|"|\')', 'adminPostFilter', 'adminPostFilterV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminPostListHeader(\s|"|\')', 'adminPostListHeader', 'adminPostListHeaderV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminPostListValue(\s|"|\')', 'adminPostListValue', 'adminPostListValueV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminPostMiniListHeader(\s|"|\')', 'adminPostMiniListHeader', 'adminPostMiniListHeaderV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminPostsActions(\s|"|\')', 'adminPostsActions', 'adminPostsActionsV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminPostsActionsPage(\s|"|\')', 'adminPostsActionsPage', 'adminPostsActionsPageV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminPreferencesForm(\s|"|\')', 'adminPreferencesForm', 'adminPreferencesFormV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminRteFlags(\s|"|\')', 'adminRteFlags', 'adminRteFlagsV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminSearchPageCombo(\s|"|\')', 'adminSearchPageCombo', 'adminSearchPageComboV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminSearchPageDisplay(\s|"|\')', 'adminSearchPageDisplay', 'adminSearchPageDisplayV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminSearchPageHead(\s|"|\')', 'adminSearchPageHead', 'adminSearchPageHeadV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminSearchPageProcess(\s|"|\')', 'adminSearchPageProcess', 'adminSearchPageProcessV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminUsersActions(\s|"|\')', 'adminUsersActions', 'adminUsersActionsV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminUsersActionsContent(\s|"|\')', 'adminUsersActionsContent', 'adminUsersActionsContentV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminUserFilter(\s|"|\')', 'adminUserFilter', 'adminUserFilterV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminUserListHeader(\s|"|\')', 'adminUserListHeader', 'adminUserListHeaderV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['adminUserListValue(\s|"|\')', 'adminUserListValue', 'adminUserListValueV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['exportFull(\s|"|\')', 'exportFull', 'exportFullV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['exportSingle(\s|"|\')', 'exportSingle', 'exportSingleV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['importExportModules(\s|"|\')', 'importExportModules', 'importExportModulesV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['importFull(\s|"|\')', 'importFull', 'importFullV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['importInit(\s|"|\')', 'importInit', 'importInitV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['importPrepareDC12(\s|"|\')', 'importPrepareDC12', 'importPrepareDC12V2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['importSingle(\s|"|\')', 'importSingle', 'importSingleV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['pluginsToolsHeaders(\s|"|\')', 'pluginsToolsHeaders', 'pluginsToolsHeadersV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['pluginsToolsTabs(\s|"|\')', 'pluginsToolsTabs', 'pluginsToolsTabsV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['restCheckStoreUpdate(\s|"|\')', 'restCheckStoreUpdate', 'restCheckStoreUpdateV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['themesToolsHeaders(\s|"|\')', 'themesToolsHeaders', 'themesToolsHeadersV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
        ['themesToolsTabs(\s|"|\')', 'themesToolsTabs', 'themesToolsTabsV2', '2.24', 'https://open-time.net/post/2022/11/06/Adapter-son-code-pour-la-224-n-17'],
    ],
];
